import "./globals.css";

export const metadata = {
  title: "XxNTxX's Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body className="bg-body">
        {children}
      </body>
    </html>
  );
}
